import 'package:vector_crisis/game/models/arrow_type.dart';
import 'package:vector_crisis/game/models/level_data.dart';

/// The ranges the campaign is generated and stored in, matching
/// tool/generate_campaign.sh.
const campaignRanges = [
  (4, 50),
  (51, 100),
  (101, 150),
  (151, 200),
  (201, 250),
  (251, 300),
];

String campaignPartName(int from, int to) =>
    'levels_${from.toString().padLeft(3, '0')}'
    '_${to.toString().padLeft(3, '0')}';

String campaignPartVariable(int from, int to) =>
    'levels${from.toString().padLeft(3, '0')}'
    'To${to.toString().padLeft(3, '0')}';

/// Renders one range of the campaign as a Dart source file.
String renderCampaignPart(List<LevelData> levels, int from, int to) {
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED BY tool/generate_levels.dart -- DO NOT EDIT BY HAND.',
    )
    ..writeln('//')
    ..writeln(
      '// Every board is solvable by construction and its targetMoves is the',
    )
    ..writeln('// solver optimum. Regenerate with:')
    ..writeln('//   tool/generate_campaign.sh')
    ..writeln()
    ..writeln("import '../../models/arrow_direction.dart';")
    ..writeln("import '../../models/arrow_seed.dart';")
    ..writeln("import '../../models/level_data.dart';")
    ..writeln()
    ..writeln('const ${campaignPartVariable(from, to)} = <LevelData>[');

  for (final level in levels) {
    buffer
      ..writeln('  LevelData(')
      ..writeln('    id: ${level.id},')
      ..writeln('    rows: ${level.rows},')
      ..writeln('    columns: ${level.columns},')
      ..writeln('    difficulty: ${level.difficulty},')
      ..writeln("    mechanicFocus: '${level.mechanicFocus}',")
      ..writeln('    targetMoves: ${level.targetMoves},');
    if (level.isChallenge) buffer.writeln('    isChallenge: true,');
    buffer.writeln('    arrows: [');
    for (final arrow in level.arrows) {
      final name = switch (arrow.type) {
        ArrowType.normal => 'normal',
        ArrowType.rotator => 'rotator',
        ArrowType.frozen => 'frozen',
        ArrowType.bomb => 'bomb',
        ArrowType.stone => 'stone',
        ArrowType.gear => 'gear',
      };
      buffer.writeln(
        '      ArrowSeed.$name(${arrow.row}, ${arrow.column}, '
        'ArrowDirection.${arrow.direction.name}),',
      );
    }
    buffer
      ..writeln('    ],')
      ..writeln('  ),');
  }

  return (buffer..writeln('];')).toString();
}
