#!/usr/bin/env bash
# Regenerates the whole campaign, one range per process, then writes the
# index that stitches the ranges together.
#
# Each range after the first is seeded with a floor above anything the range
# before it normally ends on (see tool/plan_floor.dart), so the ramp stays
# monotone across boundaries. The level tests check that; if a boundary still
# breaks, rerun the later range with --floor set to the earlier range's last
# optimum.
set -euo pipefail
cd "$(dirname "$0")/.."

ranges=("4 50" "51 100" "101 150" "151 200" "201 250" "251 300")
mkdir -p lib/game/data/campaign build/campaign_logs
rm -f lib/game/data/campaign/levels_*.dart

pids=()
for range in "${ranges[@]}"; do
  read -r from to <<<"$range"
  floor=$(dart run tool/plan_floor.dart "$from")
  log="build/campaign_logs/${from}_${to}.log"
  caffeinate -i dart run tool/generate_levels.dart "$from" "$to" --write \
    --floor="$floor" \
    >"$log" 2>&1 &
  pids+=($!)
done

status=0
for pid in "${pids[@]}"; do
  wait "$pid" || status=1
done
if [[ $status -ne 0 ]]; then
  echo "at least one range failed; see build/campaign_logs" >&2
  exit 1
fi

index=lib/game/data/campaign_levels.dart
{
  echo '// GENERATED BY tool/generate_campaign.sh -- DO NOT EDIT BY HAND.'
  echo
  echo "import '../models/level_data.dart';"
  for range in "${ranges[@]}"; do
    read -r from to <<<"$range"
    printf "import 'campaign/levels_%03d_%03d.dart';\n" "$from" "$to"
  done
  echo
  echo 'const campaignLevels = <LevelData>['
  for range in "${ranges[@]}"; do
    read -r from to <<<"$range"
    printf '  ...levels%03dTo%03d,\n' "$from" "$to"
  done
  echo '];'
} >"$index"

dart format lib/game/data >/dev/null
echo "campaign written"
