// GENERATED BY tool/generate_campaign.sh -- DO NOT EDIT BY HAND.

import '../models/level_data.dart';
import 'campaign/levels_004_050.dart';
import 'campaign/levels_051_100.dart';
import 'campaign/levels_101_150.dart';
import 'campaign/levels_151_200.dart';
import 'campaign/levels_201_250.dart';
import 'campaign/levels_251_300.dart';

const campaignLevels = <LevelData>[
  ...levels004To050,
  ...levels051To100,
  ...levels101To150,
  ...levels151To200,
  ...levels201To250,
  ...levels251To300,
];
